name: another_flutterapp
escription: A new Flutter project to store and display images.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  image_picker: ^0.8.4+4
  google_maps_flutter: ^2.0.6
  local_auth: ^2.1.8
  cupertino_icons: ^1.0.2
  google_mlkit_image_labeling: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/request.json